### ISSUE TITLE
프로젝트 생성 및 개발 환경 설정

### ISSUE THREAD

**Issue by icallitnewart** [icallitnewart/heart-crush#1]
## Description
> 프로젝트 시작을 위한 개발 환경을 구축합니다.

## Tasks
- [x] CRA(TypeScript)로 프로젝트 생성
- [x] ESLint 설치 및 설정 (Airbnb Style)
- [x] Prettier 설치 및 설정
- [x] Husky와 lint-staged를 이용한 ESLint 자동화 

## Note
없음
