### ISSUE TITLE
하트 크러쉬 후 게임 보드 재배치

### ISSUE THREAD

**Issue by icallitnewart** [icallitnewart/heart-crush#10]
## Description
> 하트 크러쉬 후 남은 빈 공간을 메꾸기 위해 위에서 하트가 떨어지고 보드 배열이 재배치된다.

## Tasks
- [x] 위에서 하트들이 빈 공간으로 떨어지는 애니메이션 모션 효과
- [x] 보드 배열 재배치
- [x] 재배치된 보드에서 하트 매칭 검사

## Note
없음
