### ISSUE TITLE
게임 종료

### ISSUE THREAD

**Issue by icallitnewart** [icallitnewart/heart-crush#15]
## Description
> 우승 여부가 판단되면 게임 종료 문구 출력 후 결과 페이지로 전환

## Tasks
- [x] 게임 종료 알림 팝업 레이아웃 및 디자인 작업
- [x] 게임 결과 팝업 레이아웃 및 디자인 작업
- [x] 게임 결과가 나오면 게임 종료 문구 출력 (fade-in 애니메이션 효과)
- [x] 잔여 MOVE 횟수에 따른 보너스 점수 계산 (MOVE가 0이 아니라면)
- [x] 게임 종료 문구 제거 (fade-out 애니메이션 효과)
- [x] 게임 결과 화면 출력
  - 승패 여부
  - 최종 점수
  - 재시도 버튼
  - (WIN) 다음 스테이지로 이동 버튼

## Note
Related issue: #14
