### ISSUE TITLE
하트 스와이프 비활성화

### ISSUE THREAD

**Issue by icallitnewart** [icallitnewart/heart-crush#16]
## Description
> 게임 플레이 중 특정 상황에서 하트 스와이프가 작동하지 않도록 비활성화 처리

## Tasks
- [x] 스와이프 시작시 비활성화
- [x] 하트 매칭 실패 후 이동했던 하트가 원위치로 복귀시 활성화
- [x] 한 MOVE의 모든 하트 크러쉬가 다 끝났을 때 활성화
- [x] 게임 종료  알림 팝업이 나올 때 비활성화

## Note
없음
