### ISSUE TITLE
Context API 관련 파일 및 상태 관리 로직 개선

### ISSUE THREAD

**Issue by icallitnewart** [icallitnewart/heart-crush#19]
## Description
> Context API 관련 파일명을 좀 더 명확하게 변경하고, 상태 관리 로직을 재정비한다.

## Tasks
- [x] constants / types 폴더에 속한 Context API 관련 파일 구조와 이름을 좀 더 직관적으로 수정
- [x] Context 종류(GameSettings, GamePlay)에 따른 dispatch 명칭 세분화
- [x] popup 전역 상태 상위 Context로 이동 (GamePlay => GameSettings)

## Note
없음
