### ISSUE TITLE
배경 음악 재생

### ISSUE THREAD

**Issue by icallitnewart** [icallitnewart/heart-crush#21]
## Description
> 1. 처음 홈 화면에 접속시 사용자에게 배경 음악이 자동 재생된다는 것을 고지하는 알림 팝업을 띄운다. 
> 2. 음표 아이콘을 클릭하여 배경 음악 재생 여부를 제어할 수 있다. 
> 3. 각 상황에 맞는 배경 음악이 재생된다.

## Tasks
- 홈 화면 배경 음악 재생
  - [x] 처음 홈 화면 접속시 게임 사운드 자동 재생 알림 팝업 띄우기
  - [x] 팝업에서 확인 버튼 클릭시 배경 음악 재생
- 게임 화면 배경 음악 재생
  - [x] 게임 시작시 배경 음악 재생
  - [x] 스테이지별로 다른 배경 음악 재생 
- 배경 음악 재생 여부 제어
  - [x] 홈/게임 화면 음표 아이콘 클릭시 배경 음악 끄기/켜기
- 배경 음악 중지
  - [x] 게임 끝나는 시점에 배경 음악 fade-out 효과 및 중지
        (+ #22 우승/패배 효과음 재생)
  

## Note
Similar issue: #22
