### ISSUE TITLE
게임 그만두기

### ISSUE THREAD

**Issue by icallitnewart** [icallitnewart/heart-crush#23]
## Description
> 게임 화면에서 홈 버튼 클릭시 게임 그만두고 홈 화면으로 전환 

## Tasks
- [x] 게임 그만두기 확인 팝업 컴포넌트 디자인 및 레이아웃 작업
- [x] 게임 화면에서 홈 버튼 클릭시 확인 팝업 띄우기
- [x] 팝업에서 YES 버튼 클릭시 홈 화면으로 전환 (NO는 팝업 닫기)

## Note
없음
