### ISSUE TITLE
게임 보드 유효성 검사

### ISSUE THREAD

**Issue by icallitnewart** [icallitnewart/heart-crush#25]
## Description
> 1. 보드에서 하트 스왑이 가능한지 여부를 알기 위해 잠재적 하트 매칭 검사를 시행한다.  
> 2. 스왑할 수 있는 하트가 있다면, 보드에 아무 조작 없이 3초의 시간이 흘렀을 때 이동할 수 있는 한쌍의 하트를 하이라이트 표시하여 힌트로 제공한다.
> 3. 없다면 바로 보드를 초기화한다.

## Tasks
- [x] 잠재적 하트 매칭 검사
  - [x] 게임 시작시 새로운 보드를 생성한 직후
  - [x] 모든 하트크러쉬가 발생하고 하나의 MOVE가 완전히 끝났을 때
- [x] 스왑 가능한 경우 3초 후 힌트 제공
  - [x] 스왑이 가능한 한 쌍의 하트에 하이라이트 (커졌다 작아졌다) 애니메이션 효과 적용
  - [x] 하이라이트 효과음 재생
- [x] 스왑 불가능한 경우 보드 초기화
  - [x] 보드에 모든 하트를 지우고 보드 초기화를 알리는 문구 출력 (2초)
  - [x] 보드 초기화하기

## Note
없음
