### ISSUE TITLE
보드 사이즈 계산 함수 리팩토링

### ISSUE THREAD

**Issue by icallitnewart** [icallitnewart/heart-crush#31]
## Description
> 보드 사이즈(rows, columns)를 계산하는 유틸 함수 분리 

## Tasks
- [x] rows와 columns를 계산하는 getBoardSize 유틸 함수 생성 
- [x] useSwipeHearts 커스텀 훅에 유틸 함수 적용
- [x] redux slice에 유틸 함수 적용
- [x] 게임 플레이 로직에 유틸 함수 적용

## Note
없음
