### ISSUE TITLE
중앙 집중식 에러 핸들링 시스템 구축

### ISSUE THREAD

**Issue by icallitnewart** [icallitnewart/heart-crush#32]
## Description
> 한 곳에서 컴포넌트 혹은 상태 관련 에러를 일관적으로 처리할 수 있도록 중앙 집중식 에러 핸들링 시스템 설계 및 구축

## Tasks
- [x] 에러 알림 UI 디자인 및 레이아웃 작업
- [x] 에러 바운더리를 이용한 렌더링 에러 처리
- [x] 리덕스 상태에서 발생한 에러 처리

## Note
없음
