### ISSUE TITLE
렌더링 및 애니메이션 최적화

### ISSUE THREAD

**Issue by icallitnewart** [icallitnewart/heart-crush#37]
## Description
> 렌더링 최적화를 하여 불필요한 리렌더링을 방지하고, 모든 환경에서 부드러운 애니메이션을 보장한다.

## Tasks
- [ ] 기본적인 렌더링 최적화
- [ ] 게임 보드 렌더링 최적화
- [ ] 게임 보드 애니메이션 최적화

## Note
없음
